on: 
  workflow_dispatch:
  push:
    branches:
      - worldofgeese-npm-publish
permissions:
  contents: read

jobs:
  release-npm:
    runs-on: macos-latest
    steps:
      - name: Set Environment Variables
        run: echo "SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-8)" >> "$GITHUB_ENV"
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: Use Node.js 18.x
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 18.x
      - name: Build package
        run: |
          yarn
          yarn build
      - name: Setup npm registry authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish edge version if pre-release
        if: github.event.release.prerelease == true
        run: |
          CURRENT_CORE_VERSION="$(node -e "console.log(require('./package.json').version);")"
          lerna version "$CURRENT_CORE_VERSION-edge.$SHORT_SHA" --no-git-tag-version --no-push --yes
          lerna publish -from-package --dist-tag edge --yes
      - name: Setup npm registry authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish packages
        if: github.event.release.prerelease != true
        run: lerna publish from-package --yes
